---
- name: Host1 configurations
  hosts: host1
  tasks:
    - name: Interface Description for Uplinks
      arista.eos.eos_interfaces:
        config:
          - description: "{{ item.desc }}"
            name: "{{ item.name }}"
            enabled: true
            mode: layer2
        state: merged
      loop: "{{ interface_desc }}"
    - name: Enable IP routing
      arista.eos.eos_config:
        lines: ip routing
    - name: Create Port-Channel1
      arista.eos.eos_lag_interfaces:
        config:
          - name: Port-Channel1
            members:
              - member: Ethernet1
                mode: "on"
              - member: Ethernet2
                mode: "on"
        state: merged
    - name: Interface VLAN for host1
      arista.eos.eos_l3_interfaces:
        config:
          - name: Port-Channel1
            ipv4:
              - address: 10.1.10.11/24
        state: merged
    - name: Add static route configuration
      arista.eos.eos_static_routes:
        config:
          - vrf: default
            address_families:
              - afi: ipv4
                routes:
                  - dest: 0.0.0.0/0
                    next_hops:
                      - forward_router_address: 10.1.10.1
        state: merged